#!/bin/bash
# ABOUTME: Creates a surge.sh account via API and configures environment
# ABOUTME: No terminal/interactive login required - works in CC Web

set -e

# Configuration
CREDENTIALS_FILE="${HOME}/.surge-credentials"
API_ENDPOINT="https://surge.surge.sh/token"

usage() {
    cat <<EOF
Usage: ./onboard.sh <email> <password>

Creates a surge.sh account (or logs into existing) via API.
Saves credentials to ~/.surge-credentials and exports to current shell.

Example:
  ./onboard.sh myemail@example.com MySecurePass123

After running, source the credentials:
  source ~/.surge-credentials

Then deploy:
  ./deploy.sh
EOF
    exit 1
}

# Validate args
if [ -z "$1" ] || [ -z "$2" ]; then
    usage
fi

EMAIL="$1"
PASSWORD="$2"

if [ ${#PASSWORD} -lt 6 ]; then
    echo "ERROR: Password must be at least 6 characters"
    exit 1
fi

echo "Creating/authenticating surge.sh account..."
echo "Email: $EMAIL"

# Call surge API with Basic Auth
RESPONSE=$(curl -s -X POST "$API_ENDPOINT" \
    -H "Content-Type: application/json" \
    -u "$EMAIL:$PASSWORD")

# Parse response (handle multi-line JSON)
TOKEN=$(echo "$RESPONSE" | tr -d '\n' | sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
ERROR=$(echo "$RESPONSE" | tr -d '\n' | sed -n 's/.*"messages"[[:space:]]*:[[:space:]]*\["\([^"]*\)".*/\1/p')

if [ -n "$TOKEN" ]; then
    echo ""
    echo "Success! Account ready."
    echo ""

    # Save credentials
    cat > "$CREDENTIALS_FILE" <<CREDS
# Surge.sh credentials - generated by onboard.sh
# Source this file: source ~/.surge-credentials
export SURGE_LOGIN='$EMAIL'
export SURGE_TOKEN='$TOKEN'
CREDS
    chmod 600 "$CREDENTIALS_FILE"

    echo "Credentials saved to: $CREDENTIALS_FILE"
    echo ""
    echo "To activate in current shell:"
    echo "  source ~/.surge-credentials"
    echo ""
    echo "Or copy these exports:"
    echo "  export SURGE_LOGIN='$EMAIL'"
    echo "  export SURGE_TOKEN='$TOKEN'"

    # Also export for current script's children (won't affect parent shell)
    export SURGE_LOGIN="$EMAIL"
    export SURGE_TOKEN="$TOKEN"
else
    echo ""
    echo "ERROR: $ERROR"
    echo ""
    echo "Full response: $RESPONSE"
    exit 1
fi
